[project]
name = "transparent-emb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "aiohttp",
    "asyncpg",
    "scikit-learn",
    "xgboost>=3.0.5",
    "matplotlib",
    "psycopg2-binary",
]
